# my-prometheus.yml

global:
  # How frequently to scrape targets by default.
  scrape_interval: 15s

  # How frequently to evaluate rules (for alerting, etc.)
  evaluation_interval: 15s

  # Optional: Attach labels to all scraped metrics
  # external_labels:
  #   monitor: 'my-monitor'

# A list of scrape configurations.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'traefik'

    # metrics_path defaults to '/metrics'
    metrics_path: '/metrics' # This is the default path Traefik exposes metrics on the entrypoint

    # Scheme defaults to 'http'.
    scheme: http

    # Static configs specifies a list of targets to scrape.
    static_configs:
      # The target is the name of the Traefik service in docker-compose ('traefik')
      # and the internal port we configured for the metrics entrypoint ('8082').
      - targets: ['traefik:8082']

  # You can add more jobs here to scrape other services that expose Prometheus metrics
  # For example, if your backend exposed metrics on port 9091:
  # - job_name: 'backend'
  #   static_configs:
  #     - targets: ['backend:9091']
